- hosts: localhost
  connection: local
  tasks: 
    - import_tasks: tasks/prerequisites.yml
      tags: [ prerequisites ] 

    - import_tasks: tasks/productivity-tools.yml
      tags: [ productivity ] 

    - import_tasks: tasks/ssh.yml
      tags: [ ssh ] 
      vars: {
        "source_key": "ssh/id_ed25519_tbriot",
        "dest_key": "~/.ssh/id_ed25519_tbriot"
      }
    - import_tasks: tasks/zsh.yml
      tags: [ zsh ] 

    - import_tasks: tasks/dotfiles.yml
      tags: [ dotfiles ] 

    - import_tasks: tasks/golang.yml
      tags: [ golang ] 
      vars: {
        "go_download_archive": "go1.24.4.linux-amd64.tar.gz"
      }
    - import_tasks: tasks/terraform.yml
      tags: [ terraform ] 
      vars: {
        "tfswitch_install_dir": "$HOME/.local/bin",
        "terraform_docs_version": "v0.20.0" 
      }
    - import_tasks: tasks/projects.yml
      tags: [ projects ] 
      vars: {
        "personal_project_dir": "~/projects/tbriot"
      }
    - import_tasks: tasks/node-setup.yml
      tags: [ node ] 

    - import_tasks: tasks/rust.yml
      tags: [ rust ] 

    - import_tasks: tasks/neovim.yml
      tags: [ neovim ] 
      vars: {
        "neovim_version": "v0.10.1",
        "neovim_install_dir": "/opt/nvim"
      }
