- hosts: localhost
  connection: local
  vars:
    source_key: .ssh/id_ed25519_tbriot
    dest_key: ~/.ssh/id_ed25519_tbriot
    personal_project_dir: ~/development/tbriot
  tasks: 
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/core-setup.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/personal-projects.yml
    - include_tasks: tasks/neovim.yml
      vars:
        - neovim_tmp_install_dir:  /tmp/neovim
        - neovim_bin_dir: ~/neovim
      tags:
        - neovim
        - install
    - include_tasks: tasks/productivity-tools.yml
    #- include_tasks: tasks/alacritty.yml
    #- include: tasks/debugger.yml
    #- include_tasks: tasks/lsp.yml
    #- include_tasks: tasks/golang.yml
