- hosts: localhost
  connection: local
  tasks: 
    - import_tasks: tasks/prerequisites.yml
      tags: [ prerequisites ] 

    - import_tasks: tasks/productivity-tools.yml
      tags: [ productivity ] 

    - import_tasks: tasks/ssh.yml
      tags: [ ssh ] 
      vars: {
        "source_key": "ssh/id_ed25519_tbriot",
        "dest_key": "~/.ssh/id_ed25519_tbriot"
      }

    - import_tasks: tasks/shell.yml
      tags: [ shell ] 

    - import_tasks: tasks/python.yml
      tags: [ python ] 

    - import_tasks: tasks/projects.yml
      tags: [ projects ] 
      vars: {
        "personal_project_dir": "~/project"
      }

    - import_tasks: tasks/dotfiles.yml
      tags: [ dotfiles ]
      vars: {
      "clone_dir": "~/project/tbriot-dotfiles",
      "bash_config_dir": "$HOME/.config/bash"
      }

    - import_tasks: tasks/aws.yml
      tags: [ aws ] 

    - import_tasks: tasks/vim.yml
      tags: [ vim ] 

    - import_tasks: tasks/golang.yml
      tags: [ golang ] 
      vars: {
        "go_download_archive": "go1.25.4.linux-amd64.tar.gz"
      }

    - import_tasks: tasks/terraform.yml
      tags: [ terraform ] 
      vars: {
        "tfswitch_install_dir": "$HOME/.local/bin",
        "terraform_docs_version": "v0.20.0" 
      }

    - import_tasks: tasks/node-setup.yml
      tags: [ node ] 

    - import_tasks: tasks/rust.yml
      tags: [ rust ] 
