- hosts: localhost
  connection: local
  tasks: 
    - import_tasks: tasks/core.yml
      tags: [ core ] 

    - import_tasks: tasks/productivity-tools.yml
      tags: [ productivity ] 

    - import_tasks: tasks/ssh.yml
      tags: [ ssh ] 
      vars:
        source_key: ssh/id_ed25519_tbriot
        dest_key: ~/.ssh/id_ed25519_tbriot

    - import_tasks: tasks/zsh.yml
      tags: [ zsh ] 

    - import_tasks: tasks/dotfiles.yml
      tags: [ dotfiles ] 

    - import_tasks: tasks/golang.yml
      tags: [ golang ] 
      vars:
        - go_download_archive: go1.21.3.linux-amd64.tar.gz 

    - import_tasks: tasks/terraform.yml
      tags: [ terraform ] 
      vars:
        - terraform_docs_version: v0.16.0 

    - import_tasks: tasks/projects.yml
      tags: [ projects ] 
      vars:
        personal_project_dir: ~/development/tbriot

    - import_tasks: tasks/neovim.yml
      tags: [ neovim ] 
      vars:
        - neovim_build_dir: /tmp/neovim
        - neovim_install_dir: ~/.local
