- hosts: localhost
  connection: local
  vars:
    source_key: .ssh/id_ed25519_tbriot
    dest_key: $HOME/.ssh/id_ed25519_tbriot
  tasks: 
    - include_tasks: tasks/ssh.yml
    #- include: tasks/git-setup.yml
    #- include: tasks/core-setup.yml
    - include_tasks: tasks/zsh-setup.yml
    #- include: tasks/personal-projects.yml
    #- include: tasks/nvim-setup.yml
    #- include: tasks/debugger.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/productivity-tools.yml
    #- include: tasks/lsp.yml
