- name: Add Alacritty PPA repo
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:aslatter/ppa
    state: present
    update_cache: true

- name: Install Alacritty package
  become: true
  ansible.builtin.apt:
    name: [ "alacritty" ]
