- name: Download Meslo Nerd Font patched for Powelevel 10k (zsh theme)
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
    dest: /usr/local/share/fonts/MesloLGS-NF-Regular.ttf
- name: Download Meslo Nerd Font patched for Powelevel 10k (zsh theme)
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
    dest: /usr/local/share/fonts/MesloLGS-NF-Bold.ttf
- name: Download Meslo Nerd Font patched for Powelevel 10k (zsh theme)
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
    dest: /usr/local/share/fonts/MesloLGS-NF-Italic.ttf
- name: Download Meslo Nerd Font patched for Powelevel 10k (zsh theme)
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
    dest: /usr/local/share/fonts/MesloLGS-NF-Bold-Italic.ttf
