- name: Download Golang
  ansible.builtin.get_url:
    url: "https://go.dev/dl/{{ go_download_archive }}"
    dest: /tmp/golang-download/

- name: Remove previous Go installation
  ansible.builtin.file:
    path: "/usr/local/go"
    state: absent
      
- name: Extract archive
  ansible.builtin.unarchive:
    src: "/tmp/golang-download/{{ go_download_archive }}"
    dest: /usr/local
