- name: Install neovim with apt
  become: true
  ansible.builtin.apt:
    name: neovim
  tags:
    - install
    - neovim
- name: Get Packer (plugin manager)
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1
  tags:
    - install
    - neovim
