- name: Remove previous Neovim install directory if existing
  become: true
  ansible.builtin.file:
    path: "{{ neovim_install_dir }}"
    state: absent

- name: Create Neovim install directory
  become: true
  ansible.builtin.file:
    path: "{{ neovim_install_dir }}"
    state: directory

- name: Download and untar pre-built Neovim archives
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim-linux64.tar.gz"
    dest: "{{ neovim_install_dir }}"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
 
# Telescope suggested dependency to speed up regexp searches
# See https://github.com/BurntSushi/ripgrep
- name: Install ripgrep tool
  become: true
  apt:
    name: [ "ripgrep" ] 
