- name: Install packages
  become: true
  apt:
    name: [ "tmux", "fzf", "i3", "jq", "tree"]

- name: Install pre-commit
  ansible.builtin.pip:
    name: pre-commit

# https://github.com/charmbracelet/glow
- name: Install Glow
  become: true
  ansible.builtin.shell: |
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
    echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
    sudo apt update && sudo apt install glow
