- name: Install zsh
  become: true
  ansible.builtin.apt:
    name: zsh

- name: Register current user (workaround to change default shell)
  shell: whoami
  register: current_user

- name: Change shell to zsh
  become: true
  ansible.builtin.shell: "chsh -s $(which zsh) {{ current_user.stdout }}"

- name: Create directory for zsh history file
  ansible.builtin.file:
    path: $XDG_CACHE_HOME/zsh
    state: directory

- name: Check if powerlevel10k theme is installed
  stat:
    path: ~/zsh-plugins/powerlevel10k
  register: powerlevel10k_stats

- name: Install powerlevel10k
  ansible.builtin.git:
    repo: https://gitee.com/romkatv/powerlevel10k.git
    dest: ~/zsh-plugins/powerlevel10k 
    depth: 1
  when: powerlevel10k_stats.stat.exists == False

- name: Create directory for fonts
  become: true
  ansible.builtin.file:
    path: /usr/local/share/fonts
    state: directory

- name: Download Meslo Nerd Font patched for Powelevel 10k (zsh theme)
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
    dest: /usr/local/share/fonts/MesloLGS-NF-Regular.ttf

- name: Download Meslo Nerd Font patched for Powelevel 10k (zsh theme)
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
    dest: /usr/local/share/fonts/MesloLGS-NF-Bold.ttf

- name: Download Meslo Nerd Font patched for Powelevel 10k (zsh theme)
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
    dest: /usr/local/share/fonts/MesloLGS-NF-Italic.ttf

- name: Download Meslo Nerd Font patched for Powelevel 10k (zsh theme)
  become: true
  ansible.builtin.get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
    dest: /usr/local/share/fonts/MesloLGS-NF-Bold-Italic.ttf

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/zsh-plugins/zsh-autosuggestions
    depth: 1
